# Generated by Django 3.2.14 on 2022-07-23 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='image',
            field=models.ImageField(default='img/default.jpg', upload_to='img/'),
        ),
    ]
