# Generated by Django 3.2.14 on 2022-07-23 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0002_alter_work_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
