# Generated by Django 3.2.14 on 2022-07-23 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0003_work_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='publish',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='work',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
