# Generated by Django 3.2.14 on 2022-07-24 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0005_auto_20220724_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='category',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='work.category'),
        ),
        migrations.AddField(
            model_name='work',
            name='update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
