# Generated by Django 3.2.14 on 2022-07-24 16:08

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0007_quillpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='content',
            field=django_quill.fields.QuillField(),
        ),
    ]
