# Generated by Django 3.2.14 on 2022-07-24 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0008_alter_work_content'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuillPost',
        ),
    ]
