# Generated by Django 3.2.14 on 2022-07-24 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0010_work_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='content',
        ),
    ]
