# Generated by Django 3.2.14 on 2022-07-24 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0012_auto_20220724_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='category',
            field=models.ManyToManyField(to='work.Category'),
        ),
    ]
