# Generated by Django 3.2.14 on 2022-07-25 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0013_alter_work_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default='img/default', upload_to='img/'),
        ),
    ]
