# Generated by Django 3.2.14 on 2022-07-26 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0014_category_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Work',
            new_name='Post',
        ),
    ]
