# Generated by Django 3.2.14 on 2022-07-27 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0015_rename_work_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='url',
            field=models.CharField(default='https://imanbayati', max_length=500),
        ),
    ]
