# Generated by Django 3.2.14 on 2022-07-27 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0016_post_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='url',
            field=models.CharField(default='https://imanbayati.github', max_length=500),
        ),
    ]
