# Generated by Django 3.2.14 on 2022-07-30 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0019_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='publish',
            field=models.DateTimeField(null=True),
        ),
    ]
