# Generated by Django 3.2.14 on 2022-07-30 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0020_comment_publish'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='publish',
        ),
    ]
